const {chromium}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || "msedge"});
  const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForSelector('.project-card');
  assert.equal(await page.locator('.project-card').count(),7);
  assert.ok(await page.getByText('Completed · Certificate pending',{exact:true}).count()>0);
  await page.screenshot({path:'artifacts/home-desktop.png'});
  await page.locator('[data-project-filter="Applied AI"]').click();
  assert.equal(await page.locator('.project-card').count(),2);
  await page.locator('[data-project-filter="Analytics & BI"]').click();
  assert.equal(await page.locator('.project-card').count(),3);
  await page.locator('[data-case="financial-fraud"]').first().click();
  await page.locator('#case-dialog[open]').waitFor();
  assert.match(await page.locator('#case-content').innerText(),/1,142/);
  await page.screenshot({path:'artifacts/financial-case.png'});
  await page.keyboard.press('Escape');
  await page.locator('[data-project-filter="all"]').click();
  await page.locator('#projects').scrollIntoViewIfNeeded();
  await page.screenshot({path:'artifacts/projects-desktop.png'});
  await page.goto('http://127.0.0.1:4173/?project=financial-fraud');
  await page.locator('#case-dialog[open]').waitFor();await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:4173/');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('#hamburger').click();assert.equal(await page.locator('#hamburger').getAttribute('aria-expanded'),'true');
  await page.locator('.mobile-link[href="#projects"]').click();
  assert.equal(await page.locator('#hamburger').getAttribute('aria-expanded'),'false');
  await page.screenshot({path:'artifacts/projects-mobile.png'});
  await page.goto('http://127.0.0.1:4173/admin/');await page.locator('#setup:not([hidden])').waitFor();
  await page.goto('http://127.0.0.1:4173/admin/?demo=1');await page.locator('#workspace:not([hidden])').waitFor();
  assert.equal(await page.locator('.project-row').count(),7);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:'artifacts/admin-mobile.png'});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'artifacts/admin-desktop.png'});
  await page.locator('#project-form [name=title]').fill('Financial Fraud Analytics — reviewed');
  await page.locator('#preview').click();await page.locator('#preview-dialog[open]').waitFor();
  await page.waitForFunction(()=>document.querySelector('#preview-content img').naturalWidth>0);
  await page.keyboard.press('Escape');
  await page.locator('#save-project').click();await page.getByText('تم حفظ المشروع ونشره.',{exact:false}).waitFor();
  assert.match(await page.locator('.project-row').first().innerText(),/reviewed/);
  await page.locator('#project-form [name=visible]').uncheck();await page.locator('#save-project').click();
  await page.getByText('تم حفظ المشروع كمخفي',{exact:false}).waitFor();assert.equal(await page.locator('#published-count').innerText(),'6');
  await page.locator('#profile-tab').click();await page.locator('#profile-form [name=availability]').fill('Open to analytics roles');
  await page.locator('#profile-form button[type=submit]').click();await page.getByText('تم حفظ ونشر بياناتك.',{exact:false}).waitFor();
  await page.locator('#projects-tab').click();
  page.once('dialog',d=>d.accept());await page.locator('#delete-project').click();
  await page.getByText('تم حذف المشروع.',{exact:false}).waitFor();assert.equal(await page.locator('.project-row').count(),6);
  await page.locator('#new-project').click();
  const added=JSON.parse(fs.readFileSync('content/projects/financial-fraud.json'));
  added.id='browser-added-project';added.title='New browser project';
  for(const key of ['id','title','category','description','image','imageAlt','problem','approach','outcome','limitations'])await page.locator(`#project-form [name=${key}]`).fill(added[key]);
  await page.locator('#project-form [name=visible]').check();
  await page.locator('#save-project').click();await page.getByText('تم حفظ المشروع ونشره.',{exact:false}).waitFor();
  assert.equal(await page.locator('.project-row').count(),7);
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/portfolio-backup/);
  assert.deepEqual(errors,[]);
  await browser.close();console.log('Browser checks passed: desktop/mobile, case deep links, filters, menu, admin preview, save, hide, delete, profile, export.');
})().catch(error=>{console.error(error);process.exitCode=1;});
