import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {renderProject} from './build.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sample = JSON.parse(fs.readFileSync(path.join(root,'content/projects/emolens.json')));
assert.match(renderProject({...sample,title:'<script>alert("x")</script>'}), /&lt;script&gt;/);
assert.throws(() => renderProject({...sample,links:[{label:'Bad',url:'javascript:alert(1)',download:false}]}));
assert.throws(() => renderProject({...sample,image:'assets/images/missing.png'}));
assert.throws(() => renderProject({...sample,visible:'false'}));
const temp = fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-check-'));
for (const folder of ['scripts','content','templates','assets']) fs.cpSync(path.join(root,folder),path.join(temp,folder),{recursive:true});
for (const file of ['style.css','script.js','.nojekyll','power-bi-projects-main.zip','مدير الحياه']) fs.cpSync(path.join(root,file),path.join(temp,file),{recursive:true});
const build = () => execFileSync(process.execPath,[path.join(temp,'scripts/build.mjs')],{encoding:'utf8',stdio:'pipe'});
const result = () => fs.readFileSync(path.join(temp,'_site/index.html'),'utf8');
build();
assert.equal((result().match(/class="project-card/g)||[]).length,6);
const projectPath = path.join(temp,'content/projects/emolens.json');
fs.writeFileSync(projectPath,JSON.stringify({...sample,visible:false}));
build();
assert.equal((result().match(/class="project-card/g)||[]).length,5);
assert.match(result(),/data-target="5"/);
fs.unlinkSync(projectPath);
build();
assert.equal((result().match(/class="project-card/g)||[]).length,5);
fs.writeFileSync(projectPath,JSON.stringify({...sample,order:0,title:'New test project'}));
build();
assert.equal((result().match(/class="project-card/g)||[]).length,6);
assert.ok(result().indexOf('New test project') < result().indexOf('Electricity Theft Detection — Dual-Branch'));
const lastGood = result();
fs.writeFileSync(projectPath,'{broken JSON');
assert.throws(build);
assert.equal(result(),lastGood);
console.log('Passed: build, hide, remove, add, order, count, escaping, invalid URLs, missing images, malformed JSON.');
